"""karar isleri, kararlar ve model cagrilari

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 13:31:50.471728

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("strategy", sa.String(length=30), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                name="jobstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "decided",
                "skipped_not_new",
                "skipped_human_edit",
                "failed_provider",
                "failed_error",
                "failed_worker_lost",
                name="joboutcome",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('decided', 'skipped_not_new', 'skipped_human_edit', 'failed_provider', 'failed_error', 'failed_worker_lost')",
            name=op.f("ck_decision_jobs_outcome"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name=op.f("ck_decision_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_decision_jobs_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_jobs")),
    )
    op.create_index(
        "ix_decision_jobs_status_run_after", "decision_jobs", ["status", "run_after"], unique=False
    )
    op.create_index("ix_decision_jobs_ticket_id", "decision_jobs", ["ticket_id"], unique=False)
    op.create_index(
        "uq_decision_jobs_open_ticket",
        "decision_jobs",
        ["ticket_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column(
            "strategy",
            sa.Enum(
                "rule_based",
                "llm_only",
                "jev_only",
                "hybrid",
                name="strategyname",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "electrical",
                "plumbing",
                "it_network",
                "cleaning",
                "other",
                name="category",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "high", name="priority", native_enum=False, length=20),
            nullable=True,
        ),
        sa.Column("missing_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_required", sa.Boolean(), nullable=False),
        sa.Column("review_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("judgments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("providers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column(
            "applied_outcome",
            sa.Enum(
                "applied",
                "skipped_not_new",
                "skipped_human_edit",
                name="applyoutcome",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applied_outcome IN ('applied', 'skipped_not_new', 'skipped_human_edit')",
            name=op.f("ck_decisions_applied_outcome"),
        ),
        sa.CheckConstraint(
            "category IN ('electrical', 'plumbing', 'it_network', 'cleaning', 'other')",
            name=op.f("ck_decisions_category"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high')", name=op.f("ck_decisions_priority")
        ),
        sa.CheckConstraint(
            "strategy IN ('rule_based', 'llm_only', 'jev_only', 'hybrid')",
            name=op.f("ck_decisions_strategy"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["decision_jobs.id"],
            name=op.f("fk_decisions_job_id_decision_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_decisions_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_index("ix_decisions_ticket_id", "decisions", ["ticket_id"], unique=False)
    op.create_index("uq_decisions_job_id", "decisions", ["job_id"], unique=True)
    op.create_table(
        "model_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "strategy",
            sa.Enum(
                "rule_based",
                "llm_only",
                "jev_only",
                "hybrid",
                name="strategyname",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=False),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ok",
                "timeout",
                "rate_limited",
                "schema_error",
                "unavailable",
                "auth_error",
                "bad_request",
                name="callstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("provider_duration_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("usage_estimated", sa.Boolean(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("request_id", sa.String(length=200), nullable=True),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "status IN ('ok', 'timeout', 'rate_limited', 'schema_error', 'unavailable', 'auth_error', 'bad_request')",
            name=op.f("ck_model_calls_status"),
        ),
        sa.CheckConstraint(
            "strategy IN ('rule_based', 'llm_only', 'jev_only', 'hybrid')",
            name=op.f("ck_model_calls_strategy"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
            name=op.f("fk_model_calls_decision_id_decisions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["decision_jobs.id"],
            name=op.f("fk_model_calls_job_id_decision_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_calls")),
    )
    op.create_index("ix_model_calls_job_id", "model_calls", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_calls_job_id", table_name="model_calls")
    op.drop_table("model_calls")
    op.drop_index("uq_decisions_job_id", table_name="decisions")
    op.drop_index("ix_decisions_ticket_id", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(
        "uq_decision_jobs_open_ticket",
        table_name="decision_jobs",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_index("ix_decision_jobs_ticket_id", table_name="decision_jobs")
    op.drop_index("ix_decision_jobs_status_run_after", table_name="decision_jobs")
    op.drop_table("decision_jobs")
    # ### end Alembic commands ###
